Application\Grossum\MenuBundle\Entity\MenuItem:
    type: entity
    table: menu_item
    repositoryClass: Application\Grossum\MenuBundle\Entity\Repository\MenuItemRepository
    id:
        id:
            type: integer
            unsigned: true
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        root:
            targetEntity: Application\Grossum\MenuBundle\Entity\MenuItem
            nullable: true
            joinColumn:
                referencedColumnName: id
                onDelete: CASCADE
            gedmo:
                - treeRoot
        parent:
            targetEntity: Application\Grossum\MenuBundle\Entity\MenuItem
            inversedBy: children
            joinColumn:
                referencedColumnName: id
                onDelete: CASCADE
            gedmo:
                - treeParent
    oneToMany:
        children:
            targetEntity: Application\Grossum\MenuBundle\Entity\MenuItem
            mappedBy: parent
            orderBy:
                lft: ASC
